name: Node CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Use Node.js 12
      uses: actions/setup-node@master
      with:
        node-version: 12
    - run: npm install -g yarn codecov snyk @zefiros/npm-defaults@next
    - name: yarn install, build, and test
      run: npm-defaults ci
      env:
        CI: "true"
    - name: coverage
      run: codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - name: release
      if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
      run: npm-defaults release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: create pull request
      if: github.ref == 'refs/heads/development'
      run: npm-defaults make-release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}